import { jsPDF } from "jspdf";
import { format } from "date-fns";

interface Msg {
  sender_id: string;
  body: string;
  created_at: string;
  attachment_name?: string | null;
}
interface Agreement {
  description: string;
  amount: number;
  status: string;
  created_at: string;
}

const FOOTER = "Generated by Collabor8 - collaborate8.com";

export function downloadChatPdf(opts: {
  myId: string;
  myName: string;
  coparentName: string;
  messages: Msg[];
  agreements: Agreement[];
}) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 48;
  let y = M;

  // Header: C8 mark + names
  doc.setFillColor(212, 160, 23);
  doc.roundedRect(M, y, 36, 36, 8, 8, "F");
  doc.setTextColor(26, 26, 24);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("C8", M + 18, y + 23, { align: "center" });
  doc.setFontSize(18);
  doc.text("Collabor8 - Financial chat record", M + 50, y + 16);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`${opts.myName} and ${opts.coparentName} · Generated ${format(new Date(), "d MMM yyyy, HH:mm")}`, M + 50, y + 32);
  y += 60;
  doc.setDrawColor(212, 160, 23);
  doc.line(M, y, W - M, y);
  y += 20;

  const ensure = (h: number) => {
    if (y + h > H - 50) {
      doc.addPage();
      y = M;
    }
  };

  const section = (t: string) => {
    ensure(30);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(26, 26, 24);
    doc.text(t, M, y);
    y += 18;
  };

  section("Messages");
  if (!opts.messages.length) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text("No messages yet.", M, y);
    y += 16;
  }
  opts.messages.forEach((m) => {
    const who = m.sender_id === opts.myId ? opts.myName : opts.coparentName;
    const body = m.body + (m.attachment_name ? ` [Attachment: ${m.attachment_name}]` : "");
    doc.setFontSize(10);
    const lines = doc.splitTextToSize(body || " ", W - M * 2);
    ensure(16 + lines.length * 13 + 10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(26, 26, 24);
    doc.text(who, M, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(120);
    doc.text(format(new Date(m.created_at), "d MMM yyyy, HH:mm"), W - M, y, { align: "right" });
    y += 14;
    doc.setTextColor(40);
    doc.text(lines, M, y);
    y += lines.length * 13 + 10;
  });

  if (opts.agreements.length) {
    y += 10;
    section("Shared expense agreements");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    opts.agreements.forEach((a) => {
      ensure(16);
      doc.setTextColor(40);
      doc.text(`${format(new Date(a.created_at), "d MMM yyyy")} - ${a.description} - £${Number(a.amount).toFixed(2)} - ${a.status === "rejected" ? "Declined" : "Agreed"}`, M, y);
      y += 16;
    });
  }

  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(130);
    doc.text(FOOTER, W / 2, H - 24, { align: "center" });
  }

  doc.save(`collabor8-chat-record-${format(new Date(), "yyyy-MM-dd")}.pdf`);
}
