project_id = "eycpkzbjylzzynkfggis"

[functions.yapily-webhook]
verify_jwt = false

[functions.stripe-connect]
verify_jwt = false

[functions.stripe-subscriptions]
verify_jwt = false

[functions.stripe-webhooks]
verify_jwt = false

[functions.send-coparent-reminder]
verify_jwt = false


[functions.process-email-queue]
verify_jwt = true
