// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.2";

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@3.0.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(auth2) {
  const token = auth2.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my Collabor8 profile",
  description: "Return the signed-in parent's Collabor8 profile: name, role (managing or viewing parent), invite code and whether a co-parent is linked.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Authenticated caller required");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("id, first_name, last_name, role, invite_code, coparent_id, created_at").eq("id", ctx.getUserId()).maybeSingle();
    if (error) throw new ToolError(error.message);
    if (!data) throw new ToolError("No profile found for the signed-in user.");
    const profile = {
      firstName: data.first_name ?? null,
      lastName: data.last_name ?? null,
      role: data.role,
      inviteCode: data.invite_code ?? null,
      coparentLinked: Boolean(data.coparent_id),
      createdAt: data.created_at
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: { profile }
    };
  }
});

// src/lib/mcp/tools/list-arrangements.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@3.0.2";
var list_arrangements_default = defineTool2({
  name: "list_maintenance_arrangements",
  title: "List child maintenance arrangements",
  description: "List the signed-in parent's recurring child maintenance arrangements, with amount in GBP, frequency, next due date and whether the arrangement is active.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Authenticated caller required");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("recurring_payments").select(
      "id, amount, frequency, day_of_month, day_of_week, next_due_date, is_active, user_id, receiver_id, created_at"
    ).order("created_at", { ascending: false });
    if (error) throw new ToolError2(error.message);
    const userId = ctx.getUserId();
    const arrangements = (data ?? []).map((row) => ({
      id: row.id,
      amountGbp: Number(row.amount),
      frequency: row.frequency,
      dayOfMonth: row.day_of_month ?? null,
      dayOfWeek: row.day_of_week ?? null,
      nextDueDate: row.next_due_date ?? null,
      isActive: row.is_active,
      myRole: row.user_id === userId ? "paying" : "receiving",
      createdAt: row.created_at
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(arrangements, null, 2) }],
      structuredContent: { arrangements }
    };
  }
});

// src/lib/mcp/tools/list-payments.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@3.0.2";
import { z } from "npm:zod@^3.25.76";
var list_payments_default = defineTool3({
  name: "list_payments",
  title: "List payments",
  description: "List the signed-in parent's Collabor8 payment history (maintenance and expense payments), newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(25).describe("How many payments to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError3("Authenticated caller required");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("payments").select("id, amount, currency, status, type, payer_id, payee_id, created_at").order("created_at", { ascending: false }).limit(limit);
    if (error) throw new ToolError3(error.message);
    const userId = ctx.getUserId();
    const payments = (data ?? []).map((row) => ({
      id: row.id,
      amount: Number(row.amount),
      currency: row.currency,
      status: row.status,
      type: row.type,
      direction: row.payer_id === userId ? "outgoing" : "incoming",
      createdAt: row.created_at
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(payments, null, 2) }],
      structuredContent: { payments }
    };
  }
});

// src/lib/mcp/tools/list-expenses.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@3.0.2";
import { z as z2 } from "npm:zod@^3.25.76";
var list_expenses_default = defineTool4({
  name: "list_expenses",
  title: "List shared expenses",
  description: "List shared one-off expense requests visible to the signed-in parent, with amount, status (pending, approved, rejected, paid) and who raised it.",
  inputSchema: {
    status: z2.enum(["pending", "approved", "rejected", "paid"]).optional().describe("Only return expenses with this status."),
    limit: z2.number().int().min(1).max(100).default(25).describe("How many expenses to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError4("Authenticated caller required");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("expense_requests").select(
      "id, description, amount, status, user_id, decided_at, applied_at, paid_at, apply_note, created_at"
    ).order("created_at", { ascending: false }).limit(limit);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) throw new ToolError4(error.message);
    const userId = ctx.getUserId();
    const expenses = (data ?? []).map((row) => ({
      id: row.id,
      description: row.description,
      amountGbp: Number(row.amount),
      status: row.status,
      raisedByMe: row.user_id === userId,
      decidedAt: row.decided_at ?? null,
      appliedAt: row.applied_at ?? null,
      paidAt: row.paid_at ?? null,
      note: row.apply_note ?? null,
      createdAt: row.created_at
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(expenses, null, 2) }],
      structuredContent: { expenses }
    };
  }
});

// src/lib/mcp/tools/create-expense.ts
import { defineTool as defineTool5, ToolError as ToolError5 } from "npm:@lovable.dev/mcp-js@3.0.2";
import { z as z3 } from "npm:zod@^3.25.76";
var create_expense_default = defineTool5({
  name: "create_expense",
  title: "Raise a shared expense",
  description: "Raise a one-off shared expense for the co-parent to approve or decline. Receipts can only be attached inside the Collabor8 app.",
  inputSchema: {
    description: z3.string().trim().min(1).max(200).describe("What the expense is for."),
    amountGbp: z3.number().positive().max(1e5).describe("Amount in GBP.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ description, amountGbp }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError5("Authenticated caller required");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("expense_requests").insert({ user_id: ctx.getUserId(), description, amount: amountGbp }).select("id, description, amount, status, created_at").single();
    if (error) throw new ToolError5(error.message);
    const expense = {
      id: data.id,
      description: data.description,
      amountGbp: Number(data.amount),
      status: data.status,
      createdAt: data.created_at
    };
    return {
      content: [
        {
          type: "text",
          text: `Expense raised for \xA3${expense.amountGbp.toFixed(2)}: ${expense.description}. Awaiting your co-parent's approval.`
        }
      ],
      structuredContent: { expense }
    };
  }
});

// src/lib/mcp/tools/list-manual-payments.ts
import { defineTool as defineTool6, ToolError as ToolError6 } from "npm:@lovable.dev/mcp-js@3.0.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_manual_payments_default = defineTool6({
  name: "list_manual_payments",
  title: "List manually recorded payments",
  description: "List payments the signed-in parent has recorded as sent from their own bank, outside Collabor8, with a running total.",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).default(25).describe("How many records to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError6("Authenticated caller required");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("manual_payments").select("id, amount, paid_on, reference, note, created_at").order("paid_on", { ascending: false }).limit(limit);
    if (error) throw new ToolError6(error.message);
    const payments = (data ?? []).map((row) => ({
      id: row.id,
      amountGbp: Number(row.amount),
      paidOn: row.paid_on,
      reference: row.reference ?? null,
      note: row.note ?? null
    }));
    const totalGbp = payments.reduce((sum, p) => sum + p.amountGbp, 0);
    return {
      content: [{ type: "text", text: JSON.stringify({ totalGbp, payments }, null, 2) }],
      structuredContent: { totalGbp, payments }
    };
  }
});

// src/lib/mcp/tools/record-manual-payment.ts
import { defineTool as defineTool7, ToolError as ToolError7 } from "npm:@lovable.dev/mcp-js@3.0.2";
import { z as z5 } from "npm:zod@^3.25.76";
var record_manual_payment_default = defineTool7({
  name: "record_manual_payment",
  title: "Record a payment sent from your own bank",
  description: "Record a maintenance payment the signed-in parent has already sent from their own bank account. Collabor8 does not move the money; this only keeps the record.",
  inputSchema: {
    amountGbp: z5.number().positive().max(1e5).describe("Amount sent, in GBP."),
    paidOn: z5.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Date the payment was sent, as YYYY-MM-DD. Defaults to today."),
    reference: z5.string().trim().max(120).optional().describe("Payment reference used."),
    note: z5.string().trim().max(300).optional().describe("Optional note about the payment.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ amountGbp, paidOn, reference, note }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError7("Authenticated caller required");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("manual_payments").insert({
      user_id: ctx.getUserId(),
      amount: amountGbp,
      ...paidOn ? { paid_on: paidOn } : {},
      ...reference ? { reference } : {},
      ...note ? { note } : {}
    }).select("id, amount, paid_on, reference, note").single();
    if (error) throw new ToolError7(error.message);
    const payment = {
      id: data.id,
      amountGbp: Number(data.amount),
      paidOn: data.paid_on,
      reference: data.reference ?? null,
      note: data.note ?? null
    };
    return {
      content: [
        {
          type: "text",
          text: `Recorded \xA3${payment.amountGbp.toFixed(2)} sent on ${payment.paidOn}.`
        }
      ],
      structuredContent: { payment }
    };
  }
});

// src/lib/mcp/tools/list-chat-messages.ts
import { defineTool as defineTool8, ToolError as ToolError8 } from "npm:@lovable.dev/mcp-js@3.0.2";
import { z as z6 } from "npm:zod@^3.25.76";
var list_chat_messages_default = defineTool8({
  name: "list_chat_messages",
  title: "List financial chat messages",
  description: "List recent messages in the financial chat between the signed-in parent and their co-parent, newest last.",
  inputSchema: {
    limit: z6.number().int().min(1).max(100).default(30).describe("How many messages to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError8("Authenticated caller required");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("messages").select("id, body, sender_id, created_at, attachment_name").order("created_at", { ascending: false }).limit(limit);
    if (error) throw new ToolError8(error.message);
    const userId = ctx.getUserId();
    const messages = (data ?? []).map((row) => ({
      id: row.id,
      body: row.body,
      fromMe: row.sender_id === userId,
      attachmentName: row.attachment_name ?? null,
      sentAt: row.created_at
    })).reverse();
    return {
      content: [{ type: "text", text: JSON.stringify(messages, null, 2) }],
      structuredContent: { messages }
    };
  }
});

// src/lib/mcp/tools/send-chat-message.ts
import { defineTool as defineTool9, ToolError as ToolError9 } from "npm:@lovable.dev/mcp-js@3.0.2";
import { z as z7 } from "npm:zod@^3.25.76";
var send_chat_message_default = defineTool9({
  name: "send_chat_message",
  title: "Send a financial chat message",
  description: "Send a text message to the signed-in parent's linked co-parent in the financial chat. Requires a linked co-parent.",
  inputSchema: {
    body: z7.string().trim().min(1).max(2e3).describe("The message text to send.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ body }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError9("Authenticated caller required");
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: profile, error: profileError } = await supabase.from("profiles").select("coparent_id").eq("id", userId).maybeSingle();
    if (profileError) throw new ToolError9(profileError.message);
    if (!profile?.coparent_id) {
      throw new ToolError9(
        "No co-parent is linked yet, so there is nobody to message. Invite your co-parent in the Collabor8 app first."
      );
    }
    const { data, error } = await supabase.from("messages").insert({ sender_id: userId, recipient_id: profile.coparent_id, body }).select("id, body, created_at").single();
    if (error) throw new ToolError9(error.message);
    const message = { id: data.id, body: data.body, sentAt: data.created_at };
    return {
      content: [{ type: "text", text: "Message sent to your co-parent." }],
      structuredContent: { message }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "eycpkzbjylzzynkfggis";
var mcp_default = defineMcp({
  name: "medi8-your-connection-hub",
  title: "Medi8: Your Connection Hub",
  version: "0.1.0",
  instructions: "Tools for Collabor8, a co-parenting finance app. Acts as the signed-in parent: read their profile and co-parent link status, read child maintenance arrangements and payment history, list and raise shared expenses, record payments sent from their own bank, and read or send messages in the financial chat. All amounts are in GBP.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_my_profile_default,
    list_arrangements_default,
    list_payments_default,
    list_expenses_default,
    create_expense_default,
    list_manual_payments_default,
    record_manual_payment_default,
    list_chat_messages_default,
    send_chat_message_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
